# Part 1: Data Preprocessing

In [1]:
# Importing the libraries
import numpy as np
import pandas as pd
# setup numpy print options to see float values upto 2 decimal
np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})

In [2]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [3]:
print (X[0:5])
print (y[0:5])

[[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]
 [608 'Spain' 'Female' 41 1 83807.86 1 0 1 112542.58]
 [502 'France' 'Female' 42 8 159660.8 3 1 0 113931.57]
 [699 'France' 'Female' 39 1 0.0 2 0 0 93826.63]
 [850 'Spain' 'Female' 43 2 125510.82 1 1 1 79084.1]]
[1 0 1 0 0]


In [4]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [5]:
print (X[0:5])

[[619 0 0 42 2 0.0 1 1 1 101348.88]
 [608 2 0 41 1 83807.86 1 0 1 112542.58]
 [502 0 0 42 8 159660.8 3 1 0 113931.57]
 [699 0 0 39 1 0.0 2 0 0 93826.63]
 [850 2 0 43 2 125510.82 1 1 1 79084.1]]


In [6]:
# one hot encoding on country (at index 1) to have dummy_france, dummy_germany, dummy_spain
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
print (X[0:5])

[[1.00 0.00 0.00 619.00 0.00 42.00 2.00 0.00 1.00 1.00 1.00 101348.88]
 [0.00 0.00 1.00 608.00 0.00 41.00 1.00 83807.86 1.00 0.00 1.00 112542.58]
 [1.00 0.00 0.00 502.00 0.00 42.00 8.00 159660.80 3.00 1.00 0.00 113931.57]
 [1.00 0.00 0.00 699.00 0.00 39.00 1.00 0.00 2.00 0.00 0.00 93826.63]
 [0.00 0.00 1.00 850.00 0.00 43.00 2.00 125510.82 1.00 1.00 1.00 79084.10]]


In [7]:
# drop first row dummy_france for avoiding dummy variable trap
X = X[:, 1:]
print (X[0:5])

[[0.00 0.00 619.00 0.00 42.00 2.00 0.00 1.00 1.00 1.00 101348.88]
 [0.00 1.00 608.00 0.00 41.00 1.00 83807.86 1.00 0.00 1.00 112542.58]
 [0.00 0.00 502.00 0.00 42.00 8.00 159660.80 3.00 1.00 0.00 113931.57]
 [0.00 0.00 699.00 0.00 39.00 1.00 0.00 2.00 0.00 0.00 93826.63]
 [0.00 1.00 850.00 0.00 43.00 2.00 125510.82 1.00 1.00 1.00 79084.10]]


In [8]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

print (X_train[0:5])
print (X_test[0:5])
print (y_train[0:5])
print (y_test[0:5])

[[0.00 1.00 667.00 0.00 34.00 5.00 0.00 2.00 1.00 0.00 163830.64]
 [1.00 0.00 427.00 1.00 42.00 1.00 75681.52 1.00 1.00 1.00 57098.00]
 [0.00 0.00 535.00 0.00 29.00 2.00 112367.34 1.00 1.00 0.00 185630.76]
 [0.00 1.00 654.00 1.00 40.00 5.00 105683.63 1.00 1.00 0.00 173617.09]
 [0.00 1.00 850.00 0.00 57.00 8.00 126776.30 2.00 1.00 1.00 132298.49]]
[[1.00 0.00 597.00 0.00 35.00 8.00 131101.04 1.00 1.00 1.00 192852.67]
 [0.00 0.00 523.00 0.00 40.00 2.00 102967.41 1.00 1.00 0.00 128702.10]
 [0.00 1.00 706.00 0.00 42.00 8.00 95386.82 1.00 1.00 1.00 75732.25]
 [0.00 0.00 788.00 1.00 32.00 4.00 112079.58 1.00 0.00 0.00 89368.59]
 [1.00 0.00 706.00 1.00 38.00 5.00 163034.82 2.00 1.00 1.00 135662.17]]
[0 0 0 0 0]
[0 1 0 0 0]


In [9]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print (X_train[0:5])
print (X_test[0:5])
print (y_train[0:5])
print (y_test[0:5])

[[-0.57 1.74 0.17 -1.09 -0.46 0.01 -1.22 0.81 0.64 -1.03 1.11]
 [1.75 -0.57 -2.30 0.92 0.30 -1.38 -0.01 -0.92 0.64 0.97 -0.75]
 [-0.57 -0.57 -1.19 -1.09 -0.94 -1.03 0.58 -0.92 0.64 -1.03 1.49]
 [-0.57 1.74 0.04 0.92 0.11 0.01 0.47 -0.92 0.64 -1.03 1.28]
 [-0.57 1.74 2.06 -1.09 1.74 1.04 0.81 0.81 0.64 0.97 0.56]]
[[1.75 -0.57 -0.55 -1.09 -0.37 1.04 0.88 -0.92 0.64 0.97 1.61]
 [-0.57 -0.57 -1.31 -1.09 0.11 -1.03 0.43 -0.92 0.64 -1.03 0.50]
 [-0.57 1.74 0.57 -1.09 0.30 1.04 0.31 -0.92 0.64 0.97 -0.42]
 [-0.57 -0.57 1.42 0.92 -0.66 -0.34 0.58 -0.92 -1.56 -1.03 -0.19]
 [1.75 -0.57 0.57 0.92 -0.08 0.01 1.39 0.81 0.64 0.97 0.62]]
[0 0 0 0 0]
[0 1 0 0 0]


# Part 2 - Now let's make the ANN!

In [ ]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

In [ ]:
# Initialising the ANN
classifier = Sequential()

In [ ]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'glorot_uniform', activation = 'relu', input_dim = 11))
# classifier.add(Dropout(p = 0.1))

In [ ]:
# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'glorot_uniform', activation = 'relu', input_dim = 6))
# classifier.add(Dropout(p = 0.1))

In [ ]:
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'glorot_uniform', activation = 'sigmoid'))

In [ ]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 30)

# Part 3 - Making predictions and evaluating the model

In [ ]:
# Keras evaluate method
score = classifier.evaluate(X_test, y_test)
print ("\n Loss and Accuracy Score:", score)

In [ ]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
print (y_pred)

In [ ]:
y_pred_bool = (y_pred > 0.5)
print (y_pred_bool)

In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_bool)

In [ ]:
print (cm)
# print (cm[[0][0]])
print (cm[[0][0]][0])
# print (cm[[1][0]])
print (cm[[1][0]][1])

In [ ]:
print ('Accuracy:', (cm[[0][0]][0] + cm[[1][0]][1]) / len(y_pred_bool))

# Part 4 - Evaluating, Improving and Tuning the ANN

In [10]:
# Evaluating the ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [11]:
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'glorot_uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'glorot_uniform', activation = 'relu', input_dim = 6))
    classifier.add(Dense(units = 1, kernel_initializer = 'glorot_uniform', activation = 'sigmoid', input_dim = 6))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

In [12]:
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 20)

# K Fold Cross Validation method from sklearn.model_selection
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)

Epoch 1/20
Epoch 1/20
Epoch 1/20
Epoch 1/20
  10/7200 [..............................] - ETA: 3s - loss: 0.4892 - acc: 0.8000
Epoch 2/20
 150/7200 [..............................] - ETA: 2s - loss: 0.4984 - acc: 0.7667
Epoch 2/20
7200/7200 [==============================] - 2s - loss: 0.4402 - acc: 0.7981     Epoch 3/20

Epoch 3/20
7140/7200 [============================>.] - ETA: 0s - loss: 0.4221 - acc: 0.8067
Epoch 4/20
7200/7200 [==============================] - 2s - loss: 0.4224 - acc: 0.8060     

Epoch 4/20

Epoch 4/20
Epoch 4/20
7200/7200 [==============================] - 2s - loss: 0.4063 - acc: 0.8167     
Epoch 5/20
 210/7200 [..............................] - ETA: 2s - loss: 0.3774 - acc: 0.8571
Epoch 5/20
7200/7200 [==============================] - 2s - loss: 0.4124 - acc: 0.8140     
Epoch 5/20
7200/7200 [==============================] - 2s - loss: 0.3893 - acc: 0.8301     
Epoch 6/20
7200/7200 [==============================] - 2s - loss: 0.3948 - acc: 0.8271     
Ep

7200/7200 [==============================] - 2s - loss: 0.3439 - acc: 0.8586     
Epoch 19/20
7200/7200 [==============================] - 2s - loss: 0.3402 - acc: 0.8596     
Epoch 20/20
7200/7200 [==============================] - 2s - loss: 0.3452 - acc: 0.8589     
Epoch 20/20
350/800 [============>.................] - ETA: 0sEpoch 1/20
Epoch 1/20
Epoch 1/20
Epoch 1/20
6750/7200 [===========================>..] - ETA: 0s - loss: 0.5229 - acc: 0.7859
Epoch 2/20
7200/7200 [==============================] - 3s - loss: 0.5198 - acc: 0.7876     
Epoch 2/20
6790/7200 [===========================>..] - ETA: 0s - loss: 0.4445 - acc: 0.8016
Epoch 3/20
7200/7200 [==============================] - 2s - loss: 0.4482 - acc: 0.8018     

7090/7200 [============================>.] - ETA: 0s - loss: 0.4454 - acc: 0.8013Epoch 3/20
Epoch 3/20
7200/7200 [==============================] - 2s - loss: 0.4465 - acc: 0.8008     
Epoch 3/20
7200/7200 [==============================] - 2s - loss: 0.4308 - a

 610/7200 [=>............................] - ETA: 2s - loss: 0.3999 - acc: 0.8279
Epoch 16/20
 370/7200 [>.............................] - ETA: 2s - loss: 0.4132 - acc: 0.8297
Epoch 16/20
7200/7200 [==============================] - 2s - loss: 0.3420 - acc: 0.8586     
Epoch 17/20
7200/7200 [==============================] - 3s - loss: 0.3415 - acc: 0.8593     
Epoch 18/20
7200/7200 [==============================] - 3s - loss: 0.3441 - acc: 0.8615     
Epoch 18/20
7200/7200 [==============================] - 3s - loss: 0.3413 - acc: 0.8604     
Epoch 18/20
7200/7200 [==============================] - 3s - loss: 0.3388 - acc: 0.8611     
Epoch 18/20
7100/7200 [============================>.] - ETA: 0s - loss: 0.3446 - acc: 0.8593
Epoch 19/20
 270/7200 [>.............................] - ETA: 2s - loss: 0.3341 - acc: 0.8741
Epoch 19/20
7200/7200 [==============================] - 2s - loss: 0.3408 - acc: 0.8594     
Epoch 19/20
7200/7200 [==============================] - 2s - loss: 0.34

In [14]:
#  now to see bias-variance tradeoff
# bias
mean = accuracies.mean()

# variance
variance = accuracies.std()

print ('mean', mean)
print ('variance',variance)

mean 0.857999995202
variance 0.0118479947021


In [ ]:
# Tuning the ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'glorot_uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'glorot_uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'glorot_uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

parameters = {'batch_size': [25, 32],
              'epochs': [100, 50],
              'optimizer': ['adam', 'rmsprop']}

grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10)
grid_search = grid_search.fit(X_train, y_train)
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

Epoch 1/100
7200/7200 [==============================] - 0s - loss: 0.5268 - acc: 0.7688     
Epoch 2/100
7200/7200 [==============================] - 0s - loss: 0.4632 - acc: 0.7961     
Epoch 3/100
7200/7200 [==============================] - 0s - loss: 0.4428 - acc: 0.7961     
Epoch 4/100
7200/7200 [==============================] - 0s - loss: 0.4331 - acc: 0.8012     
Epoch 5/100
7200/7200 [==============================] - 0s - loss: 0.4266 - acc: 0.8069     
Epoch 6/100
7200/7200 [==============================] - 0s - loss: 0.4199 - acc: 0.8121     
Epoch 7/100
7200/7200 [==============================] - 0s - loss: 0.4091 - acc: 0.8194     
Epoch 8/100
7200/7200 [==============================] - 0s - loss: 0.3960 - acc: 0.8281     
Epoch 9/100
7200/7200 [==============================] - 0s - loss: 0.3835 - acc: 0.8367     
Epoch 10/100
7200/7200 [==============================] - 0s - loss: 0.3742 - acc: 0.8440     
Epoch 11/100
7200/7200 [==============================] - 0

7200/7200 [==============================] - 0s - loss: 0.3328 - acc: 0.8650     
Epoch 87/100
7200/7200 [==============================] - 0s - loss: 0.3332 - acc: 0.8650     
Epoch 88/100
7200/7200 [==============================] - 0s - loss: 0.3328 - acc: 0.8665     
Epoch 89/100
7200/7200 [==============================] - 0s - loss: 0.3330 - acc: 0.8649     
Epoch 90/100
7200/7200 [==============================] - 0s - loss: 0.3329 - acc: 0.8653     
Epoch 91/100
7200/7200 [==============================] - 0s - loss: 0.3328 - acc: 0.8661     
Epoch 92/100
7200/7200 [==============================] - 0s - loss: 0.3328 - acc: 0.8656     
Epoch 93/100
7200/7200 [==============================] - 0s - loss: 0.3322 - acc: 0.8642     
Epoch 94/100
7200/7200 [==============================] - 0s - loss: 0.3327 - acc: 0.8662     
Epoch 95/100
7200/7200 [==============================] - 0s - loss: 0.3327 - acc: 0.8647     
Epoch 96/100
7200/7200 [==============================] - 0s - 

7200/7200 [==============================] - 0s - loss: 0.3904 - acc: 0.8410     
Epoch 72/100
7200/7200 [==============================] - 0s - loss: 0.3900 - acc: 0.8415     
Epoch 73/100
7200/7200 [==============================] - 0s - loss: 0.3903 - acc: 0.8399     
Epoch 74/100
7200/7200 [==============================] - 0s - loss: 0.3900 - acc: 0.8425     
Epoch 75/100
7200/7200 [==============================] - 0s - loss: 0.3900 - acc: 0.8400     
Epoch 76/100
7200/7200 [==============================] - 0s - loss: 0.3898 - acc: 0.8418     
Epoch 77/100
7200/7200 [==============================] - 0s - loss: 0.3900 - acc: 0.8414     
Epoch 78/100
7200/7200 [==============================] - 0s - loss: 0.3898 - acc: 0.8407     
Epoch 79/100
7200/7200 [==============================] - 0s - loss: 0.3896 - acc: 0.8419     
Epoch 80/100
7200/7200 [==============================] - 0s - loss: 0.3894 - acc: 0.8414     
Epoch 81/100
7200/7200 [==============================] - 0s - 

7200/7200 [==============================] - 0s - loss: 0.3366 - acc: 0.8612     
Epoch 57/100
7200/7200 [==============================] - 0s - loss: 0.3366 - acc: 0.8614     
Epoch 58/100
7200/7200 [==============================] - 0s - loss: 0.3364 - acc: 0.8610     
Epoch 59/100
7200/7200 [==============================] - 0s - loss: 0.3362 - acc: 0.8614     
Epoch 60/100
7200/7200 [==============================] - 0s - loss: 0.3363 - acc: 0.8606     
Epoch 61/100
7200/7200 [==============================] - 0s - loss: 0.3362 - acc: 0.8610     
Epoch 62/100
7200/7200 [==============================] - 0s - loss: 0.3360 - acc: 0.8608     
Epoch 63/100
7200/7200 [==============================] - 0s - loss: 0.3363 - acc: 0.8631     
Epoch 64/100
7200/7200 [==============================] - 0s - loss: 0.3358 - acc: 0.8612     
Epoch 65/100
7200/7200 [==============================] - 0s - loss: 0.3363 - acc: 0.8625     
Epoch 66/100
7200/7200 [==============================] - 0s - 

7200/7200 [==============================] - 0s - loss: 0.3376 - acc: 0.8637     
Epoch 42/100
7200/7200 [==============================] - 0s - loss: 0.3375 - acc: 0.8644     
Epoch 43/100
7200/7200 [==============================] - 0s - loss: 0.3367 - acc: 0.8629     
Epoch 44/100
7200/7200 [==============================] - 0s - loss: 0.3364 - acc: 0.8625     
Epoch 45/100
7200/7200 [==============================] - 0s - loss: 0.3364 - acc: 0.8637     
Epoch 46/100
7200/7200 [==============================] - 0s - loss: 0.3358 - acc: 0.8639     
Epoch 47/100
7200/7200 [==============================] - 0s - loss: 0.3359 - acc: 0.8650     
Epoch 48/100
7200/7200 [==============================] - 0s - loss: 0.3356 - acc: 0.8649     
Epoch 49/100
7200/7200 [==============================] - 0s - loss: 0.3352 - acc: 0.8647     
Epoch 50/100
7200/7200 [==============================] - 0s - loss: 0.3349 - acc: 0.8647     
Epoch 51/100
7200/7200 [==============================] - 0s - 

7200/7200 [==============================] - 0s - loss: 0.3718 - acc: 0.8437     
Epoch 27/100
7200/7200 [==============================] - 0s - loss: 0.3701 - acc: 0.8454     
Epoch 28/100
7200/7200 [==============================] - 0s - loss: 0.3686 - acc: 0.8464     
Epoch 29/100
7200/7200 [==============================] - 0s - loss: 0.3675 - acc: 0.8479     
Epoch 30/100
7200/7200 [==============================] - 0s - loss: 0.3660 - acc: 0.8485     
Epoch 31/100
7200/7200 [==============================] - 0s - loss: 0.3649 - acc: 0.8490     
Epoch 32/100
7200/7200 [==============================] - 0s - loss: 0.3636 - acc: 0.8506     
Epoch 33/100
7200/7200 [==============================] - 0s - loss: 0.3628 - acc: 0.8499     
Epoch 34/100
7200/7200 [==============================] - 0s - loss: 0.3614 - acc: 0.8510     
Epoch 35/100
7200/7200 [==============================] - 0s - loss: 0.3603 - acc: 0.8506     
Epoch 36/100
7200/7200 [==============================] - 0s - 

7200/7200 [==============================] - 0s - loss: 0.3666 - acc: 0.8450     
Epoch 12/100
7200/7200 [==============================] - 0s - loss: 0.3617 - acc: 0.8492     
Epoch 13/100
7200/7200 [==============================] - 0s - loss: 0.3589 - acc: 0.8512     
Epoch 14/100
7200/7200 [==============================] - 0s - loss: 0.3565 - acc: 0.8515     
Epoch 15/100
7200/7200 [==============================] - 0s - loss: 0.3548 - acc: 0.8528     
Epoch 16/100
7200/7200 [==============================] - 0s - loss: 0.3533 - acc: 0.8539     
Epoch 17/100
7200/7200 [==============================] - 0s - loss: 0.3520 - acc: 0.8558     
Epoch 18/100
7200/7200 [==============================] - 0s - loss: 0.3504 - acc: 0.8556     
Epoch 19/100
7200/7200 [==============================] - 0s - loss: 0.3504 - acc: 0.8567     
Epoch 20/100
7200/7200 [==============================] - 0s - loss: 0.3493 - acc: 0.8564     
Epoch 21/100
7200/7200 [==============================] - 0s - 

7200/7200 [==============================] - 0s - loss: 0.3347 - acc: 0.8637     
Epoch 98/100
7200/7200 [==============================] - 0s - loss: 0.3343 - acc: 0.8643     
Epoch 99/100
7200/7200 [==============================] - 0s - loss: 0.3346 - acc: 0.8637     
Epoch 100/100
7200/7200 [==============================] - 1s - loss: 0.5608 - acc: 0.6908     
Epoch 2/100
7200/7200 [==============================] - 0s - loss: 0.4532 - acc: 0.8012     
Epoch 3/100
7200/7200 [==============================] - 0s - loss: 0.4256 - acc: 0.8132     
Epoch 4/100
7200/7200 [==============================] - 0s - loss: 0.4040 - acc: 0.8243     
Epoch 5/100
7200/7200 [==============================] - 0s - loss: 0.3865 - acc: 0.8351     
Epoch 6/100
7200/7200 [==============================] - 0s - loss: 0.3761 - acc: 0.8407     
Epoch 7/100
7200/7200 [==============================] - 0s - loss: 0.3700 - acc: 0.8429     
Epoch 8/100
7200/7200 [==============================] - 0s - loss: 

7200/7200 [==============================] - 0s - loss: 0.3321 - acc: 0.8624     
Epoch 83/100
7200/7200 [==============================] - 0s - loss: 0.3317 - acc: 0.8624     
Epoch 84/100
7200/7200 [==============================] - 0s - loss: 0.3322 - acc: 0.8632     
Epoch 85/100
7200/7200 [==============================] - 0s - loss: 0.3317 - acc: 0.8628     
Epoch 86/100
7200/7200 [==============================] - 0s - loss: 0.3320 - acc: 0.8618     
Epoch 87/100
7200/7200 [==============================] - 0s - loss: 0.3318 - acc: 0.8635     
Epoch 88/100
7200/7200 [==============================] - 0s - loss: 0.3318 - acc: 0.8615     
Epoch 89/100
7200/7200 [==============================] - 0s - loss: 0.3314 - acc: 0.8640     
Epoch 90/100
7200/7200 [==============================] - 0s - loss: 0.3319 - acc: 0.8643     
Epoch 91/100
7200/7200 [==============================] - 0s - loss: 0.3314 - acc: 0.8615     
Epoch 92/100
7200/7200 [==============================] - 0s - 

7200/7200 [==============================] - 0s - loss: 0.3307 - acc: 0.8624     
Epoch 68/100
7200/7200 [==============================] - 0s - loss: 0.3309 - acc: 0.8624     
Epoch 69/100
7200/7200 [==============================] - 0s - loss: 0.3307 - acc: 0.8615     
Epoch 70/100
7200/7200 [==============================] - 0s - loss: 0.3306 - acc: 0.8617     
Epoch 71/100
7200/7200 [==============================] - 0s - loss: 0.3309 - acc: 0.8633     
Epoch 72/100
7200/7200 [==============================] - 0s - loss: 0.3300 - acc: 0.8628     
Epoch 73/100
7200/7200 [==============================] - 0s - loss: 0.3304 - acc: 0.8624     
Epoch 74/100
7200/7200 [==============================] - 0s - loss: 0.3304 - acc: 0.8610     
Epoch 75/100
7200/7200 [==============================] - 0s - loss: 0.3305 - acc: 0.8608     
Epoch 76/100
7200/7200 [==============================] - 0s - loss: 0.3305 - acc: 0.8606     
Epoch 77/100
7200/7200 [==============================] - 0s - 

7200/7200 [==============================] - 0s - loss: 0.3328 - acc: 0.8633     
Epoch 53/100
7200/7200 [==============================] - 0s - loss: 0.3336 - acc: 0.8637     
Epoch 54/100
7200/7200 [==============================] - 0s - loss: 0.3328 - acc: 0.8649     
Epoch 55/100
7200/7200 [==============================] - 0s - loss: 0.3320 - acc: 0.8639     
Epoch 56/100
7200/7200 [==============================] - 0s - loss: 0.3325 - acc: 0.8644     
Epoch 57/100
7200/7200 [==============================] - 0s - loss: 0.3316 - acc: 0.8654     
Epoch 58/100
7200/7200 [==============================] - 0s - loss: 0.3323 - acc: 0.8628     
Epoch 59/100
7200/7200 [==============================] - 0s - loss: 0.3314 - acc: 0.8647     
Epoch 60/100
7200/7200 [==============================] - 0s - loss: 0.3318 - acc: 0.8626     
Epoch 61/100
7200/7200 [==============================] - 0s - loss: 0.3317 - acc: 0.8635     
Epoch 62/100
7200/7200 [==============================] - 0s - 

7200/7200 [==============================] - 0s - loss: 0.3460 - acc: 0.8587     
Epoch 38/100
7200/7200 [==============================] - 0s - loss: 0.3463 - acc: 0.8582     
Epoch 39/100
7200/7200 [==============================] - 0s - loss: 0.3462 - acc: 0.8586     
Epoch 40/100
7200/7200 [==============================] - 0s - loss: 0.3458 - acc: 0.8590     
Epoch 41/100
7200/7200 [==============================] - 0s - loss: 0.3455 - acc: 0.8585     
Epoch 42/100
7200/7200 [==============================] - 0s - loss: 0.3458 - acc: 0.8590     
Epoch 43/100
7200/7200 [==============================] - 0s - loss: 0.3450 - acc: 0.8587     
Epoch 44/100
7200/7200 [==============================] - 0s - loss: 0.3451 - acc: 0.8579     
Epoch 45/100
7200/7200 [==============================] - 0s - loss: 0.3449 - acc: 0.8597     
Epoch 46/100
7200/7200 [==============================] - 0s - loss: 0.3447 - acc: 0.8607     
Epoch 47/100
7200/7200 [==============================] - 0s - 

7200/7200 [==============================] - 0s - loss: 0.3621 - acc: 0.8531     
Epoch 23/100
7200/7200 [==============================] - 0s - loss: 0.3603 - acc: 0.8557     
Epoch 24/100
7200/7200 [==============================] - 0s - loss: 0.3595 - acc: 0.8551     
Epoch 25/100
7200/7200 [==============================] - 0s - loss: 0.3581 - acc: 0.8551     
Epoch 26/100
7200/7200 [==============================] - 0s - loss: 0.3574 - acc: 0.8571     
Epoch 27/100
7200/7200 [==============================] - 0s - loss: 0.3563 - acc: 0.8576     
Epoch 28/100
7200/7200 [==============================] - 0s - loss: 0.3551 - acc: 0.8576     
Epoch 29/100
7200/7200 [==============================] - 0s - loss: 0.3550 - acc: 0.8585     
Epoch 30/100
7200/7200 [==============================] - 0s - loss: 0.3539 - acc: 0.8614     
Epoch 31/100
7200/7200 [==============================] - 0s - loss: 0.3532 - acc: 0.8593     
Epoch 32/100
7200/7200 [==============================] - 0s - 

7200/7200 [==============================] - 0s - loss: 0.4093 - acc: 0.8075     
Epoch 8/100
7200/7200 [==============================] - 0s - loss: 0.3988 - acc: 0.8200     
Epoch 9/100
7200/7200 [==============================] - 0s - loss: 0.3898 - acc: 0.8308     
Epoch 10/100
7200/7200 [==============================] - 0s - loss: 0.3825 - acc: 0.8371     
Epoch 11/100
7200/7200 [==============================] - 0s - loss: 0.3768 - acc: 0.8418     
Epoch 12/100
7200/7200 [==============================] - 0s - loss: 0.3726 - acc: 0.8457     
Epoch 13/100
7200/7200 [==============================] - 0s - loss: 0.3689 - acc: 0.8485     
Epoch 14/100
7200/7200 [==============================] - 0s - loss: 0.3657 - acc: 0.8536     
Epoch 15/100
7200/7200 [==============================] - 0s - loss: 0.3631 - acc: 0.8533     
Epoch 16/100
7200/7200 [==============================] - 0s - loss: 0.3614 - acc: 0.8542     
Epoch 17/100
7200/7200 [==============================] - 0s - lo

7200/7200 [==============================] - 0s - loss: 0.3344 - acc: 0.8631     
Epoch 94/100
7200/7200 [==============================] - 0s - loss: 0.3338 - acc: 0.8637     
Epoch 95/100
7200/7200 [==============================] - 0s - loss: 0.3338 - acc: 0.8632     
Epoch 96/100
7200/7200 [==============================] - 0s - loss: 0.3341 - acc: 0.8640     
Epoch 97/100
7200/7200 [==============================] - 0s - loss: 0.3338 - acc: 0.8644     
Epoch 98/100
7200/7200 [==============================] - 0s - loss: 0.3335 - acc: 0.8628     
Epoch 99/100
7200/7200 [==============================] - 0s - loss: 0.3339 - acc: 0.8646     
Epoch 100/100
7200/7200 [==============================] - 0s - loss: 0.5850 - acc: 0.7276     
Epoch 2/100
7200/7200 [==============================] - 0s - loss: 0.4872 - acc: 0.7964     
Epoch 3/100
7200/7200 [==============================] - 0s - loss: 0.4563 - acc: 0.8022     
Epoch 4/100
7200/7200 [==============================] - 0s - lo

In [ ]:
print (best_parameters)
print (best_accuracy)